// .pi/extensions/swarm-mail.ts
// Generated by pi-swarm — do not edit manually.
// Agent: builder-1 | Mail: /root/NRL-Predict/.pi-swarm/mail.json
//
// Provides inter-agent messaging within a swarm run.
// Inspired by Overstory's SQLite mail system, simplified to JSON.

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import * as fs from "node:fs";
import * as crypto from "node:crypto";

const AGENT_NAME = "builder-1";
const MAIL_PATH = "/root/NRL-Predict/.pi-swarm/mail.json";

interface MailMessage {
  id: string;
  from: string;
  to: string;
  subject: string;
  body: string;
  type: string;
  read: boolean;
  createdAt: string;
}

interface MailStore {
  messages: MailMessage[];
}

function readStore(): MailStore {
  try {
    if (fs.existsSync(MAIL_PATH)) {
      return JSON.parse(fs.readFileSync(MAIL_PATH, "utf-8")) as MailStore;
    }
  } catch {}
  return { messages: [] };
}

function writeStore(store: MailStore): void {
  const tmp = MAIL_PATH + ".tmp";
  fs.writeFileSync(tmp, JSON.stringify(store, null, 2), "utf-8");
  fs.renameSync(tmp, MAIL_PATH);
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "swarm_mail",
    label: "Swarm Mail",
    description: [
      "Inter-agent messaging within a swarm. Use this to communicate with other builders running in parallel.",
      "Actions:",
      "  send — Send a message (to, subject, body required). Use type 'api_created' when you create a function/module other builders need.",
      "  check — Check your inbox for unread messages from other builders.",
      "  list — List all messages (optional filters: from, type).",
      "IMPORTANT: After creating any shared function, module, or API that other builders might import,",
      "immediately send an api_created message to 'all' describing the function signature and import path.",
    ].join(" "),
    promptSnippet: [
      "swarm_mail lets you communicate with other builders in the swarm.",
      "After creating shared code (functions, classes, modules), ALWAYS send an api_created message:",
      '  swarm_mail({ action: "send", to: "all", type: "api_created", subject: "get_historical_bars()", body: "from brokers.alpaca.market_data import get_historical_bars\\nSignature: get_historical_bars(symbols: list[str], start: str, end: str) -> dict[str, pd.DataFrame]" })',
      "Check for messages from other builders periodically:",
      '  swarm_mail({ action: "check" })',
    ].join("\n"),
    parameters: Type.Object({
      action: Type.String({ description: "send | check | list" }),
      to: Type.Optional(Type.String({ description: "Recipient: agent name, 'all', or 'coordinator' (for send)" })),
      subject: Type.Optional(Type.String({ description: "Message subject (for send)" })),
      body: Type.Optional(Type.String({ description: "Message body (for send)" })),
      type: Type.Optional(Type.String({ description: "Message type: status | api_created | question | result | worker_done | error (default: status)" })),
      from: Type.Optional(Type.String({ description: "Filter by sender (for list)" })),
    }),
    async execute(_toolCallId, params) {
      const action = params.action?.trim().toLowerCase();

      if (action === "send") {
        if (!params.to || !params.subject || !params.body) {
          return {
            content: [{ type: "text", text: "Error: send requires 'to', 'subject', and 'body' parameters." }],
            isError: true,
          };
        }
        const store = readStore();
        const msg: MailMessage = {
          id: "msg-" + crypto.randomBytes(6).toString("hex"),
          from: AGENT_NAME,
          to: params.to,
          subject: params.subject,
          body: params.body,
          type: params.type || "status",
          read: false,
          createdAt: new Date().toISOString(),
        };
        store.messages.push(msg);
        writeStore(store);
        return {
          content: [{ type: "text", text: `Sent ${msg.type} message to ${msg.to}: "${msg.subject}" (id: ${msg.id})` }],
        };
      }

      if (action === "check") {
        const store = readStore();
        const unread: MailMessage[] = [];
        for (const msg of store.messages) {
          if (!msg.read && (msg.to === AGENT_NAME || msg.to === "all") && msg.from !== AGENT_NAME) {
            msg.read = true;
            unread.push(msg);
          }
        }
        if (unread.length > 0) writeStore(store);

        if (unread.length === 0) {
          return { content: [{ type: "text", text: "No new messages." }] };
        }

        let text = `${unread.length} new message(s):\n\n`;
        for (const msg of unread) {
          const tag = msg.type !== "status" ? ` [${msg.type.toUpperCase()}]` : "";
          text += `--- From: ${msg.from}${tag} ---\nSubject: ${msg.subject}\n${msg.body}\n\n`;
        }
        return { content: [{ type: "text", text }] };
      }

      if (action === "list") {
        const store = readStore();
        let msgs = store.messages;
        if (params.from) msgs = msgs.filter((m) => m.from === params.from);
        if (params.type) msgs = msgs.filter((m) => m.type === params.type);

        if (msgs.length === 0) {
          return { content: [{ type: "text", text: "No messages found." }] };
        }

        let text = `${msgs.length} message(s):\n\n`;
        for (const msg of msgs) {
          const readMark = msg.read ? " " : "*";
          text += `${readMark} [${msg.type}] ${msg.from} → ${msg.to}: ${msg.subject} (${msg.createdAt})\n`;
        }
        return { content: [{ type: "text", text }] };
      }

      return {
        content: [{ type: "text", text: "Unknown action: " + action + ". Use send, check, or list." }],
        isError: true,
      };
    },
  });
}
