// .pi/extensions/swarm-guard.ts
// Generated by pi-swarm — do not edit manually.
// Agent: builder-4 | Capability: builder
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const AGENT_NAME = "builder-4";
const CAPABILITY = "builder";
const WORKTREE_PATH = "/root/NRL-Predict/.pi-swarm/worktrees/builder-4";
const IS_READ_ONLY = false;
const ALLOWED_FILES: string[] = ["predict_round.py"];
const HAS_ALLOWLIST = true;

const WRITE_TOOLS = new Set(["write", "edit", "Write", "Edit"]);

// Swarm tools are forbidden inside agent sessions — prevents recursive swarm launches
const BLOCKED_TOOLS = new Set([
  "swarm", "swarm_plan", "swarm_merge", "swarm_status", "swarm_cleanup",
]);

const DANGEROUS_BASH = [
  /\bgit\s+push\b/,
  /\bgit\s+reset\s+--hard/,
  /\bgit\s+checkout\s+-b\s+(?!swarm\/)/,
  /\bgit\s+branch\s+-[dD]\b/,
  /\brm\s+-rf\s+\//,
];

const FILE_MODIFYING_BASH = [
  /\bsed\s+-i/,
  /\bsed\s+--in-place/,
  /echo\s+.*>/,
  /printf\s+.*>/,
  /cat\s+.*>/,
  /\btee\s/,
  /\bmv\s/,
  /\bcp\s/,
  /\brm\s/,
  /\bmkdir\s/,
  /\btouch\s/,
  />>/,
];

const SAFE_BASH_PREFIXES = [
  "git status", "git diff", "git log", "git show", "git branch",
  "ls", "cat", "head", "tail", "wc", "find", "grep", "rg",
  "echo ", "pwd", "which", "env", "date", "whoami",
  "npm test", "npm run", "npx ", "bun test", "bun run",
  "python -m pytest", "cargo test", "go test", "make test",
];

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event) => {
    // 0. Block swarm tools — agents must not spawn nested swarms
    if (BLOCKED_TOOLS.has(event.toolName)) {
      return {
        block: true,
        reason: `Recursive swarm call blocked: ${event.toolName} is not allowed inside a swarm agent. Complete your task directly using code tools.`,
      };
    }

    // 1. Block dangerous git operations (all agents)
    if (event.toolName === "bash") {
      const cmd = String((event.input as any)?.command ?? "");
      for (const pattern of DANGEROUS_BASH) {
        if (pattern.test(cmd)) {
          return { block: true, reason: `Blocked: ${cmd.slice(0, 60)}... — dangerous git operation not allowed in swarm agents` };
        }
      }
    }

    // 2. Read-only enforcement
    if (IS_READ_ONLY) {
      // Block write/edit tools
      if (WRITE_TOOLS.has(event.toolName)) {
        return {
          block: true,
          reason: `${CAPABILITY} agents are read-only — ${event.toolName} is not allowed. Report your findings instead.`,
        };
      }

      // Block file-modifying bash commands
      if (event.toolName === "bash") {
        const cmd = String((event.input as any)?.command ?? "");
        const trimmed = cmd.trimStart();
        if (SAFE_BASH_PREFIXES.some((p) => trimmed.startsWith(p))) {
          return; // Allow safe commands
        }
        for (const pattern of FILE_MODIFYING_BASH) {
          if (pattern.test(cmd)) {
            return {
              block: true,
              reason: `${CAPABILITY} agents are read-only — this bash command modifies files`,
            };
          }
        }
      }
    }

    // 3. Path boundary for builders (write/edit must stay in worktree)
    if (!IS_READ_ONLY && WRITE_TOOLS.has(event.toolName)) {
      const filePath = String(
        (event.input as any)?.path ?? (event.input as any)?.file_path ?? "",
      );
      if (filePath && !filePath.startsWith(WORKTREE_PATH + "/") && filePath !== WORKTREE_PATH) {
        // Allow relative paths (they resolve within cwd which is the worktree)
        if (filePath.startsWith("/")) {
          return {
            block: true,
            reason: "Path boundary: file is outside your assigned worktree. All writes must target files within your worktree.",
          };
        }
      }
    }

    // 3b. File allowlist for builders (write/edit must target owned files)
    if (HAS_ALLOWLIST && WRITE_TOOLS.has(event.toolName)) {
      const filePath = String(
        (event.input as any)?.path ?? (event.input as any)?.file_path ?? "",
      );
      if (filePath) {
        // Normalize to relative path for matching
        let relPath = filePath;
        if (relPath.startsWith(WORKTREE_PATH + "/")) {
          relPath = relPath.slice(WORKTREE_PATH.length + 1);
        }
        // Strip leading ./ if present
        if (relPath.startsWith("./")) {
          relPath = relPath.slice(2);
        }
        const isAllowed = ALLOWED_FILES.some((allowed) => {
          // Exact match
          if (relPath === allowed) return true;
          // Allow new files in the same directory as an owned file
          // (e.g. tests alongside source)
          if (relPath.endsWith(".pyc") || relPath.endsWith(".pyo")) return true;
          return false;
        });
        if (!isAllowed) {
          return {
            block: true,
            reason: `File ownership violation: ${relPath} is not in your assigned files [${ALLOWED_FILES.join(", ")}]. Only modify files you own.`,
          };
        }
      }
    }

    // 4. Path boundary for builders (bash file-modifying commands)
    if (!IS_READ_ONLY && event.toolName === "bash") {
      const cmd = String((event.input as any)?.command ?? "");
      if (FILE_MODIFYING_BASH.some((re) => re.test(cmd))) {
        const tokens = cmd.split(/\s+/);
        const absPaths = tokens.filter((t) => t.startsWith("/")).map((t) => t.replace(/[";>]*$/, ""));
        for (const p of absPaths) {
          if (!p.startsWith("/dev/") && !p.startsWith("/tmp/") &&
              !p.startsWith(WORKTREE_PATH + "/") && p !== WORKTREE_PATH) {
            return {
              block: true,
              reason: "Path boundary: bash command targets a path outside your worktree.",
            };
          }
        }
      }
    }

    // Default: allow
  });
}
